### PR TITLE
Draft: Optimize csrsv

### PR DESCRIPTION
**Pull request by ex-rzr**
Summary of proposed changes:
- "Optimize csrsv: scalarize wid" helps the compiler generate faster code. When `wid` is a scalar value (and pointers are const and restricted), it is possible to use scalar loads instead of vector loads for row, row_begin, row_end.
(Perhaps it's better to wrap it as a template function).
With this change we observe -5% of csrsv_kernel's duration in one application.
- "Optimize csrsv: pack "done" flags (32 per uint)" reduces the amount of memory to load when some lanes depend on neighboring rows so they can load one common uint instead of unique uints. Also less memory (32x) is need to be cleared.
About -15% of csrsv_kernel's duration in one application.

All changes are independent, I can split them into separate PR if you want.

### CODE REVIEW

**Comment by jsandham** [comment]
Hello and thanks for the PR! I ran some performance benchmarks using this PR and got the following results:

[dcsrsv_MI100_bandwidth_asic2.pdf](https://github.com/ROCmSoftwarePlatform/rocSPARSE/files/10115720/dcsrsv_MI100_bandwidth_asic2.pdf)
[dcsrsv_MI100_msec_log_asic2.pdf](https://github.com/ROCmSoftwarePlatform/rocSPARSE/files/10115722/dcsrsv_MI100_msec_log_asic2.pdf)
[dcsrsv_MI200_bandwidth.pdf](https://github.com/ROCmSoftwarePlatform/rocSPARSE/files/10115723/dcsrsv_MI200_bandwidth.pdf)
[dcsrsv_MI200_msec_log.pdf](https://github.com/ROCmSoftwarePlatform/rocSPARSE/files/10115724/dcsrsv_MI200_msec_log.pdf)
[scsrsv_NAVI21_bandwidth.pdf](https://github.com/ROCmSoftwarePlatform/rocSPARSE/files/10115725/scsrsv_NAVI21_bandwidth.pdf)
[scsrsv_NAVI21_msec_log.pdf](https://github.com/ROCmSoftwarePlatform/rocSPARSE/files/10115726/scsrsv_NAVI21_msec_log.pdf)

What this seems to indicate is that while for some matrices a speed-up can be seen, for many the proposed changes seem to result in a slow down. I think the reason for this might be that because atomics operate on bytes and not bits, then any row/columns in the done array that happen to land in the same int32 end up competing when calling the atomicOr. With this in mind I tried changing your lines:

constexpr unsigned int done_bits = CHAR_BIT * sizeof(unsigned int);

to 

constexpr unsigned int done_bits = CHAR_BIT * sizeof(uint8_t);

which at least then gives each row/column in the done array its own byte (rather than bit). This seems to help, but still is often slower then the original code. Given this, do you mind splitting up the PR into three? I think we want the log changes and probably the loading of wid into scalar registers but the changes to the done array may require some more investigation and/or tweeking to see if we can improve the performance more consistently. By having the loading of wid into scalar registers isolated to its own PR, I can also more easily benchmark that change in isolation.

**Comment by ex-rzr** [comment]
Extracted an independent change: https://github.com/ROCmSoftwarePlatform/rocSPARSE/pull/268

**Comment by ex-rzr** [comment]
I spent some time trying to understand why some cases become faster, others - slower.
Atomic conflicts can't be the cause because `atomicOr(..., 0)` is optimized to globally coherent load (`global_load_dword ... glc`,). And atomics that set the done flag called very rarely compared to reading done flags.

I took 3 different cases from rocSPARSE test matrices (ASIC_320k, rma10, bmw3_2) and 2 cases from PETSc.

table

One of big differences is that PETSc cases are more "uniform": each row has at most 27 values, there are no "bottleneck"-rows (when multiple rows depend on one row, or vice versa, a row depends on multiple rows). As a result, most lanes don't wait for other rows to finish for thousands of iterations.

The most interesting case is **rma10**: it is almost 3 times slower with my changes!
Here are omniperf results for this case.
Original code:
1_0_develop_rma10_mi200

My changes:
1_1_opt_csrsv_rma10_mi200

Th number of L1-L2 reads ("Rd:" between "Vector L1 Cache" and "L2 Cache") becomes 3.3x smaller but L2 latency ("L2 Cache: Latency") is 8x higher! It seems that are more channel conflicts. At least that's how I understand why latency is so high and "Stalled on L2 Data" is >90%.

As an experiment, I checked how `atomicOr(&done_array[local_col / done_bits * 32], 0)` would perform (https://github.com/StreamHPC/rocSPARSE/tree/opt_csrsv_mul32):
1_2_opt_csrsv_mul32_rma10_mi200

It's interesting that this change returns the original performance (see the table, column opt_csrsv_mul32). Though it also mostly cancels improvements for PETSc cases.

**ASIC_320k**, on the other hand, has non-uniform numbers of request per channel and very high latency for both branches (develop and mine). It may be explained by a row which is a dependency of many other rows, but I'm not sure:
0_0_develop_ASIC_320k_mi200

If you want to check omniperf results for other cases, I'm attaching screenshots: [omniperf-screenshots.zip](https://github.com/ROCmSoftwarePlatform/rocSPARSE/files/10276818/omniperf-screenshots.zip)

Another observation: `csrsv_analysis_lower_kernel` seems significantly faster than `csrsv_kernel` for rma10 and ASIC_320k. I wonder why. `csrsv_kernel` should process rows in a more optimal order that the original order used by `csrsv_analysis_lower_kernel`. Could it be that with the original order there are less channel conflicts? Or is it something else?

I don't know if my observation have any use. Please share your ideas why it works this way.
It doesn't seem that there is a solid condition for choosing one approach or another for any matrix. Now I understand what you have to deal with: it's really difficult to cover all possible cases with the best performance :)

Also, I've pushed `wid` "scalarization" commit here: https://github.com/StreamHPC/rocSPARSE/tree/scalar_wid
If you have time it would be great to benchmark it.

**Comment by ntrost57** [comment]
Does it make a difference when swapping `atomicOr()` with `__hip_atomic_load()` and `__hip_atomic_store()`?

We have checked the `wid` scalarization. If you can file a PR with it, I will merge it. You can skip the if condition btw, logical and hardware wavefront size will always match in this case.

**Comment by jsandham** [comment]
Performance for scalar_wid (not I removed the if statement when measuring as per Nico's comment)

[scsrsv_MI100_bandwidth_asic2.pdf](https://github.com/ROCmSoftwarePlatform/rocSPARSE/files/10297387/scsrsv_MI100_bandwidth_asic2.pdf)

**Comment by ex-rzr** [comment]
> Does it make a difference when swapping `atomicOr()` with `__hip_atomic_load()` and `__hip_atomic_store()`?

`__hip_atomic_load(&done_array[local_col], __ATOMIC_RELAXED, __HIP_MEMORY_SCOPE_AGENT)` produces exactly the same ISA as `atomicOr(&done_array[local_col], 0)`:
```
global_load_dword v16, v[6:7], off glc
```
(as I expected).

`__hip_atomic_store(&done_array[row], 1, __ATOMIC_RELAXED, __HIP_MEMORY_SCOPE_AGENT)` leads to
```
global_store_dword v[2:3], v0, off
```
compared to `atomicOr(&done_array[row], 1)`'s:
```
global_atomic_or v[2:3], v0, off
```
`global_store_dword` seems just a bit faster but I can't say for sure if it is not a fluctuation.

The same instruction can be produced with `atomicOr(&done_array[row], -1)` (all bits are set, `any_value | -1 == -1 `, so the compiler optimizes atomic min as store).

> We have checked the `wid` scalarization. If you can file a PR with it, I will merge it. You can skip the if condition btw, logical and hardware wavefront size will always match in this case.

Done.

**Pull request closed without merging**
